### ISSUE TITLE
[BUG] Clearing Search Input With Click Broken

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v48-tier1-team-04#78]
**Describe the problem**
Clearing the search input with the x icon on the search does not register as a change, so all dinosaurs do not render.

**Actual behavior**
The filtered dinosaurs do not update when we clear the search input using the "x" icon.

**Expected behavior**
When pressing the "x" button, the full ist of dinosaurs should be displayed.

**To Reproduce**
1. Go to our main page.
2. Type in a search criteria
3. Press the "x" icon within the search field

**Screenshots**
![image](https://github.com/chingu-voyages/v48-tier1-team-04/assets/33106391/d576387c-d1c5-4145-9783-b46a189fd18b)

**Your Environment:**
- Edition	Windows 10 Home
- Version	22H2
- Installed on	‎3/‎13/‎2021
- OS build	19045.4046
- Experience	Windows Feature Experience Pack 1000.19053.1000.0
 - Google Chrome Version 123.0.6312.86 (Official Build) (64-bit)
 - Any other software that may impact this issue

**Additional Information**
All that needs to really be done to prevent (allow this) to happen is to add an event listener on the input change as well.

**Comment by sebastiandlq** [comment]
Ok, was testing. And seems that the event 'input' is better than 'keyup'. Input can also detect when you pressed X
